project 'MDBSocials.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MDBSocials' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MDBSocials
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'MKSpinner'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'ChameleonFramework'
  pod 'PromiseKit'
  pod 'ObjectMapper'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift.git', :branch => 'feature/swift-3'
  pod 'LyftSDK/API'
  pod 'LocationPicker'
  pod 'Spring'

  
  target 'MDBSocialsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MDBSocialsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
